### PR TITLE
Review of webapp helm charts

### PR DESCRIPTION
**Pull request by pantierra**
Based on the tutorial @emmanuelmathot is giving @ciaransweet and myself this PR introduces some adjustments to make the `basic webapp-polder` work.

~~This PR is draft for now as it depends on https://github.com/developmentseed/polder/pull/14 It will be rerolled after the first PR got in.~~

### CODE REVIEW

**Comment by ciaransweet** [comment]
Is it worth us modifying the workflow that's failing to extract the version from the right place?

**Comment by pantierra** [comment]
Sure, next PR with the general `polder` helm chart is going to fix it (#16)

**Review by ciaransweet — APPROVED** [review]

**Review by emmanuelmathot — APPROVED** [review]
LGTM

**Comment by emmanuelmathot** [comment]
@pantierra make sure to align version in both python project file and CHarts.yaml to make tests pass

**Pull request merged**
